config/routes.rb
IndigenousLiteracyFoundation::Application.routes.draw do

  root :to => "dashboard#index"

  get 'dashboard' => 'dashboard#index'
  
  resources :excitement_pages do
    resources :testimonials
    resources :community_sections
    member do
      get 'email_list'
      post 'send_email'
      get 'show_image'
    end
    resources :books    
  end

  resources :communities
  resources :photos do
      member do
      get 'show_image'
    end
  end

  get 'community_profiles/load_communities' => 'community_profiles#load_communities'
  resources :community_profiles
end

app/models/excitement_page.rb
class ExcitementPage < ActiveRecord::Base

  has_one :photo , as: :imageable
  has_one :testimonial
  has_one :community_section
  has_many :books, dependent: :destroy

  has_one :book_section 

  validates_presence_of :title, :intro_text, :summary_text
end

app/controllers/excitement_pages_controller.rb
class ExcitementPagesController < ApplicationController
  before_action :set_excitement_page, only: [:show, :edit, :update, :destroy,:email_list,:send_email,:show_image]

  # GET /excitement_pages
  # GET /excitement_pages.json
  def index
    @excitement_pages = ExcitementPage.all
  end

  # GET /excitement_pages/1
  # GET /excitement_pages/1.json
  def show
  end

  # GET /excitement_pages/new
  def new
    @excitement_page = ExcitementPage.new
  end

  # GET /excitement_pages/1/edit
  def edit
  end

  def show_image
    puts "params #{params}"
    photo = @excitement_page.photo
    puts "HERERRERERRERERER************************"
    send_data photo.raw_data, :type => 'image/png',:disposition => 'inline'
  end

  # POST /excitement_pages
  # POST /excitement_pages.json
  def create

    puts "**************************************   #{params}"
    @excitement_page = ExcitementPage.new(excitement_page_params)

    respond_to do |format|
      if @excitement_page.save
        format.html { redirect_to edit_excitement_page_path(@excitement_page), notice: 'Excitement page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @excitement_page }
      else
        format.html { render action: 'new' }
        format.json { render json: @excitement_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /excitement_pages/1
  # PATCH/PUT /excitement_pages/1.json
  def update
    respond_to do |format|
      if @excitement_page.update(excitement_page_params)
        format.html { redirect_to @excitement_page, notice: 'Excitement page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @excitement_page.errors, status: :unprocessable_entity }
      end
    end
  end

  def email_list
    client = ILF::RestForceClient.new
    @contacts = client.donors_since(Date.today - 3.month)
  end

  def send_email
    puts "**************   got here  #{params}"
    ExcitementPageMailer.sample_mail(params[:email_address], @excitement_page, "http://#{request.domain}:#{request.port}").deliver
    flash[:notice] = "The email has been sent"
    redirect_to email_list_excitement_page_path(@excitement_page)
  end

  # DELETE /excitement_pages/1
  # DELETE /excitement_pages/1.json
  def destroy
    @excitement_page.destroy
    respond_to do |format|
      format.html { redirect_to excitement_pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_excitement_page
      @excitement_page = ExcitementPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def excitement_page_params
      params.require(:excitement_page).permit(:title, :intro_text,:summary_text)
    end
end

app/helpers/excitement_pages_helper.rb
module ExcitementPagesHelper
end

app/views/excitement_pages/_form.html.erb
<%= form_for(@excitement_page,:html => { :multipart => true }) do |f| %>
  <% if @excitement_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@excitement_page.errors.count, "error") %> prohibited this excitement_page from being saved:</h2>

      <ul>
      <% @excitement_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :intro_text %><br>
    <%= f.text_area :intro_text %>
  </div>

  <div class="field">
    <%= f.label :summary_text %><br>
    <%= f.text_area :summary_text %>
  </div>

  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-primary'  %>
  </div>

<% end %>

<script type="text/javascript">
  jQuery(function($) {
    var showUpload = $('#show-upload');
    var upload = $('#upload').hide();

    showUpload.click(function() {
      upload.show();
      showUpload.hide();
    })
  });
</script>

app/views/excitement_pages/edit.html.erb
<h1>Editing excitement_page</h1>

<% unless @excitement_page.testimonial %>
	<td><%= link_to 'Testimonial', new_excitement_page_testimonial_path(@excitement_page), { :class => "btn btn-default" } %></td>
<%else%>
	<td><%= link_to 'Testimonial', edit_excitement_page_testimonial_path(@excitement_page,@excitement_page.testimonial), { :class => "btn btn-default" } %></td>
<%end%>

<% unless @excitement_page.community_section %>
	<td><%= link_to 'Community Section', new_excitement_page_community_section_path(@excitement_page), { :class => "btn btn-default" } %></td>
<%else%>
	<td><%= link_to 'Community Section', edit_excitement_page_community_section_path(@excitement_page,@excitement_page.community_section), { :class => "btn btn-default" } %></td>
<%end%>

<%= link_to 'Books', excitement_page_books_path(@excitement_page), { :class => "btn btn-default" } %>

<%= render 'form' %>

<%= link_to 'Show', @excitement_page, { :class => "btn btn-default" } %> |
<%= link_to 'Back', excitement_pages_path, { :class => "btn btn-default" } %>

app/views/excitement_pages/email_list.html.erb
<h1>Email List</h1>

  <div class="container">
    <% flash.each do |key, value| %>
        <div class="<%=key%>"><%= value %></div>
      <% end %>
    <%= yield %>
  </div>


   <div><%= @contacts.length %> people to be emailed</div>
  <table class="table">
        <tr>
          <th>Email</th>
          <th>Last Donated</th>
        </tr>
        <% @contacts.each do |contact| %>
          <tr>
          <td><%= contact.Email %></td>
          <td><%= contact.Last_Donation_Date__c %></td>
          </tr>
        <% end %>
      </div>  
   </table>


<div id="send_email_section">
   <div class="row">
  <%= form_tag(send_email_excitement_page_path, :method => "post") do %>
        <div>
          <%= label_tag(:email_address, "Email Address") %>
          <%= text_field_tag(:email_address) %>
        </div>
      </div>
      <div>
        <div>
          <%= submit_tag("Send Test Email", id: "send_email", :class => 'btn btn-primary' ) %>       
        </div>
      </div>
  <% end %>
</div>

app/views/excitement_pages/index.html.erb
<h1>Listing Excitement Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @excitement_pages.each do |excitement_page| %>
      <tr>
        <td><%= excitement_page.title %></td>
        <td><%= link_to 'Show', excitement_page, { :class => "btn btn-default" } %></td>
        <td><%= link_to 'Edit', edit_excitement_page_path(excitement_page), { :class => "btn btn-default" } %></td>
        <td><%= link_to 'Email', email_list_excitement_page_path(excitement_page), { :class => "btn btn-default" } %></td>
        <td><%= link_to 'Destroy', excitement_page, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Excitement Page', new_excitement_page_path, { :class => "btn btn-default" } %>

app/views/excitement_pages/new.html.erb
<h1>New Excitement Page</h1>
<%= render 'form' %>




<%= link_to 'Back', excitement_pages_path, { :class => "btn btn-default" } %>

app/views/excitement_pages/show.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<h1><%= @excitement_page.title %></h1>
<p><%= @excitement_page.intro_text %></p>
<hr>

<div id="community">
    <h2>Where we helped <%= @excitement_page.community_section.community.name %> </h2>
    <div id="demographics">
      <% unless @excitement_page.community_section.community.latitude.nil? || @excitement_page.community_section.community.longitude.nil? %>
        <div id="map-canvas"></div>
      <% end %> 
    </div>    
 
    <section class="community-photo">
        <%= image_tag show_image_photo_url(@excitement_page.community_section.photo) ,:size => '260x180'%>
    </section>    
    <p class="community-text"><%= @excitement_page.community_section.community_text%> </p>
    </div> 
<hr>

<div id="testimonials">
    <h2>Who you helped</h2>
    <section class="testimonial-photo">        
        <%= image_tag show_image_photo_url(@excitement_page.testimonial.photo) ,:size => '260x180'%>
        <p><%= @excitement_page.testimonial.photo_caption %></p>
    </section>
    <section class="testimonial-text">
        <p><%= @excitement_page.testimonial.text_block %></p>
        <span>- <%= @excitement_page.testimonial.speaker_name %>,</span>
        <p><%= @excitement_page.testimonial.speaker_role %></p>
    </section>
</div> 
<hr>

<h2>Books you helped us send</h2>
<% if @excitement_page.books %>
  <div class="book-list-container">
    <% @excitement_page.books.each do |book| %>
      <div class="book-container">
        <div class="book-image"><%= image_tag show_image_photo_url(book.photo) ,:size => '260x180' if book.photo %></div>
        <div class="book-name"><strong><%= book.name %></strong></div>
      </div>
    <% end %>
  </div>
<% end %>
<hr>

<h2><%= @excitement_page.summary_text %></h2>
<a href="https://www.indigenousliteracyfoundation.org.au/payment/donate">
    <p class="donate">DONATE</p>
</a>
<br>
<br>

<%= link_to 'Edit', edit_excitement_page_path(@excitement_page), { :class => "btn btn-default" } %> |
<%= link_to 'Back', excitement_pages_path, { :class => "btn btn-default" } %>


<script type="text/javascript">
  $(function() {
    function initialize() {

      var mapOptions = {
        center: new google.maps.LatLng(<%= @excitement_page.community_section.community.latitude %>,<%= @excitement_page.community_section.community.longitude %>),
        zoom: 6
      };
      var map = new google.maps.Map(document.getElementById("map-canvas"),
          mapOptions);
      var infowindow = new google.maps.InfoWindow({
          content: "<%= @excitement_page.community_section.community.name %>"
      });
      var marker = new google.maps.Marker({
            position: new google.maps.LatLng(<%= @excitement_page.community_section.community.latitude %>,<%= @excitement_page.community_section.community.longitude %>),
            map: map,
            title: "<%= @excitement_page.community_section.community.name %>"
        });
      google.maps.event.addListener(marker, 'click', function() {
        infowindow.open(map,marker);
      });
    }
    google.maps.event.addDomListener(window, 'load', initialize);
  });
</script>