config/routes.rb
IndigenousLiteracyFoundation::Application.routes.draw do

  root :to => "dashboard#index"

  get 'dashboard' => 'dashboard#index'
  
  resources :excitement_pages do
    resources :testimonials
    resources :community_sections
    member do
      get 'email_list'
      post 'send_email'
      get 'show_image'
    end
    resources :books    
  end

  resources :communities
  resources :photos do
      member do
      get 'show_image'
    end
  end

  get 'community_profiles/load_communities' => 'community_profiles#load_communities'
  resources :community_profiles
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@communities = Community.order(:state, :name)

    today = Time.now
    start_of_year = today.beginning_of_year
    start_of_month_last_year = today - 1.year
    start_of_year_last_year = start_of_year - 1.year

    client = ILF::RestForceClient.new
  	@donations_ytd = client.donations(start_of_year, today)
  	@donations_ytd_lastyear = client.donations(start_of_year_last_year, start_of_month_last_year)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div id="donations">
	<div class="gauge-container">
    <ul class="gauge">
  		<li>
  			<strong><%= number_to_currency(@donations_ytd) %></strong>
  			<span>Year to date donations</span>
  		</li>
  		<li>
  			<strong><%= number_to_currency(@donations_ytd_lastyear) %></strong>
  			<span>Donated last year at this time</span>
  		</li>
  	</ul>
  </div>

  <div class="progress-container">
    <div class="progress">
      <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= @donations_ytd/900000 * 100 %>%;">
        <span class="sr-only"><%= @donations_ytd/900000 * 100 %>% Complete</span>
      </div>
    </div>
  </div>
</div>

<div id="demographics" style="width:100%">
  <div id="map"></div>
  
  <div id="communities">

    <% if @communities.length == 0 %>
      No communities loaded yet <%= link_to 'Load Communities', community_profiles_load_communities_path, :class => "btn btn-default" %>
    <% else %>
      <%= @communities.length %> communities
      <ul>
        <% @communities.each_with_index do |community, index| %>
          <li><%= link_to community.name, 'javascript:void(0);', :onclick=>"infoOpen('#{index}');" %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  var gmarkers = [];
  $(function() {
    function initialize() {
      var mapOptions = {
        center: new google.maps.LatLng(-24.994167,134.866944),
        zoom: 4
      };
      var map = new google.maps.Map(document.getElementById("map"),
          mapOptions);
      <% @communities.each_with_index do |community, index| %>
        <% if community.latitude && community.longitude %>
          var infowindow_<%= index %> = new google.maps.InfoWindow({
              content: '<%= link_to community.name, community_path(community.id) %>'
          });
          var marker_<%= index %> = new google.maps.Marker({
                position: new google.maps.LatLng(<%= community.latitude %>,<%= community.longitude %>),
                map: map,
                title: "<%= community.name %>"
            });
          gmarkers["<%= index %>"] = marker_<%= index %>;
          google.maps.event.addListener(marker_<%= index %>, 'click', function() {
            infowindow_<%= index %>.open(map,marker_<%= index %>);
              map.setCenter(marker_<%= index %>.getPosition());
              map.setZoom(8);
          });
        <% end %>
      <% end %>
    }
    google.maps.event.addDomListener(window, 'load', initialize);


  });
  function infoOpen(marker)
  {
      google.maps.event.trigger(gmarkers[marker],'click');
  }
</script>