config/routes.rb
IndigenousLiteracyFoundation::Application.routes.draw do

  root :to => "dashboard#index"

  get 'dashboard' => 'dashboard#index'
  
  resources :excitement_pages do
    resources :testimonials
    resources :community_sections
    member do
      get 'email_list'
      post 'send_email'
      get 'show_image'
    end
    resources :books    
  end

  resources :communities
  resources :photos do
      member do
      get 'show_image'
    end
  end

  get 'community_profiles/load_communities' => 'community_profiles#load_communities'
  resources :community_profiles
end

app/models/community_profile.rb
class CommunityProfile < ActiveRecord::Base
  belongs_to :community
  has_one :photo, as: :imageable, :dependent => :destroy
end

app/controllers/community_profiles_controller.rb
class CommunityProfilesController < ApplicationController
  before_action :set_community_profile, only: [:show, :edit, :update, :destroy]

  def index
    @community_profiles = CommunityProfile.all
  end

  def show
  end

  def new
    @community_profile = CommunityProfile.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if params[:photo]
        photo = Photo.find_by(imageable_type: 'CommunityProfile', imageable_id: @community_profile.id)
        if photo
          photo.update_attributes(raw_data: params[:photo].read)
        else
          photo = Photo.create(raw_data: params[:photo].read, imageable_type: 'CommunityProfile', imageable_id: @community_profile.id)
        end
        @community_profile.photo = photo
      end
      
      if @community_profile.update(community_profile_params)
        format.html { redirect_to @community_profile, notice: 'Community profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @community_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def load_communities
    ILF::SalesForceService.load_communities
    redirect_to community_profiles_path
  end

  private
    def set_community_profile
      @community_profile = CommunityProfile.find(params[:id])
    end

    def community_profile_params
      params.require(:community_profile).permit(:bio)
    end
end

app/helpers/community_profile_helper.rb
module CommunityProfileHelper
end

app/helpers/community_profiles_helper.rb
module CommunityProfilesHelper
end

app/views/community_profiles/_form.html.erb
<%= form_for(@community_profile, :html => { :multipart => true }) do |f| %>
  <% if @community_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community_profile.errors.count, "error") %> prohibited this community_profile from being saved:</h2>

      <ul>
      <% @community_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio, :cols => "100", :rows => "10" %>
  </div>

  <div class="field">
    <%= f.label :photo %><br>
    <%= file_field_tag :photo %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', :class => "btn btn-default" %>
    <%= link_to 'Cancel', @community_profile, :class => "btn btn-default" %>
  </div>
<% end %>

app/views/community_profiles/edit.html.erb
<h1>Editing <%= @community_profile.community.name %></h1>

<%= render 'form' %>

<%= link_to 'Back to Communities Profiles', community_profiles_path, :class => "btn btn-default" %>

app/views/community_profiles/index.html.erb
<h1>Listing community_profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @community_profiles.each do |community_profile| %>
      <tr>
        <td><%= community_profile.community.name %></td>
        <td><%= link_to 'Show', community_profile, { :class => "btn btn-default" } %></td>
        <td><%= link_to 'Edit', edit_community_profile_path(community_profile), { :class => "btn btn-default" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Load Communities', community_profiles_load_communities_path %>

app/views/community_profiles/show.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<h2><%= @community_profile.community.name %></h2>

<%= image_tag show_image_photo_url(@community_profile.photo) ,:size => '260x180' if @community_profile.photo %>

<p>
  <strong>Bio:</strong>
  <%= @community_profile.bio %>
</p>

<%= link_to 'Edit', edit_community_profile_path(@community_profile), { :class => "btn btn-default" } %> |
<%= link_to 'Back to Communities Profiles', community_profiles_path, :class => "btn btn-default" %>