config/routes.rb
IndigenousLiteracyFoundation::Application.routes.draw do

  root :to => "dashboard#index"

  get 'dashboard' => 'dashboard#index'
  
  resources :excitement_pages do
    resources :testimonials
    resources :community_sections
    member do
      get 'email_list'
      post 'send_email'
      get 'show_image'
    end
    resources :books    
  end

  resources :communities
  resources :photos do
      member do
      get 'show_image'
    end
  end

  get 'community_profiles/load_communities' => 'community_profiles#load_communities'
  resources :community_profiles
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :excitement_page
  has_one :photo, as: :imageable, :dependent => :destroy
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_excitement_page
  before_action :set_book , only: [:edit, :update, :show_image]

  def index
    @books = Book.where(excitement_page: @excitement_page)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.excitement_page = @excitement_page
   
    if @book.save
      @book.photo = Photo.create(raw_data: params[:photo].read, imageable_type: 'Book', imageable_id: @book.id)
      redirect_to excitement_page_books_path(excitement_page_id: @excitement_page), notice: 'Book was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if params[:photo]
      photo = Photo.find_by(imageable_type: 'Book', imageable_id: @book.id)
      if photo
        photo.update_attributes(raw_data: params[:photo].read)
      else
        photo = Photo.create(raw_data: params[:photo].read, imageable_type: 'Book', imageable_id: @book.id)
      end
      @book.photo = photo
    end

    if @book.update(book_params)
      redirect_to excitement_page_books_path(excitement_page_id: @excitement_page), notice: 'Book was successfully updated.'
    else
      render action: 'edit'
    end
  end

  private

    def set_excitement_page
      @excitement_page = ExcitementPage.find(params[:excitement_page_id])
    end

    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:name, :isbn)
    end

end

app/views/books/_form.html.erb
<%= form_for([@excitement_page, @book], :html => { :multipart => true }) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= image_tag show_image_photo_url(@book.photo) ,:size => '260x180' if @book.photo %>
    <%= f.label :photo %><br>
    <%= file_field_tag :photo %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', :class => "btn btn-default" %>
    <%= link_to 'Cancel', excitement_page_books_path(excitement_page_id: @excitement_page), :class => "btn btn-default" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render 'form' %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<%= link_to 'Back to excitement page', edit_excitement_page_path(@excitement_page), { :class => "btn btn-default" } %>
<%= link_to 'New', new_excitement_page_book_path, { :class => "btn btn-default glyphicon glyphicon-plus" } %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= link_to 'Edit', edit_excitement_page_book_path(excitement_page_id: @excitement_page, id: book), { :class => "btn btn-default" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render 'form' %>

<%= link_to 'Back', excitement_page_books_path, { :class => "btn btn-default" } %>